"""initial schema

Revision ID: 96db89ddb95c
Revises: 
Create Date: 2026-07-17 21:59:55.350997
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '96db89ddb95c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('query_key', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'query_key', name='uq_provider_cache_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('progress_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('progress_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('borrowed_by', sa.Text(), nullable=True),
    sa.Column('loaned_date', sa.Date(), nullable=True),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', title)", persisted=True), nullable=True),
    sa.CheckConstraint("format IN ('physical', 'digital')", name='ck_items_format'),
    sa.CheckConstraint("status IN ('wishlist', 'backlog', 'in_progress', 'completed', 'abandoned')", name='ck_items_status'),
    sa.CheckConstraint("type IN ('book', 'movie', 'game')", name='ck_items_type'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5 AND rating * 2 = floor(rating * 2)', name='ck_items_rating_half_steps'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_title_tsv', 'items', ['title_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_items_user_completed_at', 'items', ['user_id', 'completed_at'], unique=False, postgresql_where=sa.text('completed_at IS NOT NULL'))
    op.create_index('ix_items_user_format', 'items', ['user_id', 'format'], unique=False)
    op.create_index('ix_items_user_type_status', 'items', ['user_id', 'type', 'status'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_events_item_id', 'activity_events', ['item_id'], unique=False)
    op.create_index('ix_activity_events_type_created', 'activity_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_activity_events_user_created', 'activity_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_events_user_created', table_name='activity_events')
    op.drop_index('ix_activity_events_type_created', table_name='activity_events')
    op.drop_index('ix_activity_events_item_id', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_items_user_type_status', table_name='items')
    op.drop_index('ix_items_user_format', table_name='items')
    op.drop_index('ix_items_user_completed_at', table_name='items', postgresql_where=sa.text('completed_at IS NOT NULL'))
    op.drop_index('ix_items_title_tsv', table_name='items', postgresql_using='gin')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('provider_cache')
    # ### end Alembic commands ###
